### ISSUE TITLE
Conversão do código (bytecode) descrito no editor para array de Numbers

### ISSUE THREAD

**Issue by LonelehKitten** [LonelehKitten/AssemblerSimulator#52]
Para que o requestRun e requestBySteps funcione, é necessário converter o bytecode descrito pelo usuário no editor para um array de Number quando os respectivos botões (ver opções de debug) forem pressionados.

**Arquivo _header.jsx_:**
![image](https://user-images.githubusercontent.com/27026887/137230824-405ab750-1ad1-4dbb-8268-2809a8a881a2.png)

Nesse caso a string que vem do editor deve conter apenas caracteres de 0 a 9 e A a F (maiusculas e/ou minusculas) e podem estar separados por 1 ou mais espaços.
Na conversão é necessário tratar os espaços, verificar se a quantidade de hexadecimais é par, capturar os valores da string e converter (cada 2 hexadecimais é convertido para 1 Number e colocado no array).
O array resultante da conversão deve ser retornado pela função.

Exemplo de síntaxe no editor:
```
a0 ff bc4Aff f F a 5 4 f
1234 CaD 0202 9F B a1f 2
```
Note que há um número par de hexadecimais.

**Comment by fernandOlle** [comment]
favor testar implementação
